apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: samples-config-service
  name: samples-config-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: samples-config-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: samples-config-service
  name: samples-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samples-config-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: samples-config-service
    spec:
      containers:
      - image: flomesh/samples-config-service:latest
        name: samples-config-service
        env:
        - name: K8S_SERVICE_NAME
          value: samples-config-service    
        - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
          value: samples-discovery-server
        - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
          value: "8761"              
        resources: {}
status: {}
